### ISSUE TITLE
Error message when booting alpine linux machine

### ISSUE THREAD

**Issue by joaocc** [spil-ruslan/vagrant-box-updater#13]
```
config.vm.box = "maier/alpine-3.3.1-x86_64"
config.vm.box_check_update = true
```

and

```
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
/tmp/xx/.vagrant.d/gems/gems/vagrant-box-updater-0.0.3/lib/vagrant-box-updater/util/common.rb:7:in `get_path_box_stat_file': uninitialized constant Psych::ENGINE (NameError)
    from /tmp/xx/.vagrant.d/gems/gems/vagrant-box-updater-0.0.3/lib/vagrant-box-updater/action/up_box.rb:19:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
    from /opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
    from /opt/vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by lmilbaum** [comment]
+1

**Comment by ppouliot** [comment]
+2
